name: Build App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    if: contains(github.event.base_ref, 'refs/heads/main')
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma client
        run: bun run db:generate

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun run build:win

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            dist/*.exe
            dist/latest.yml

  build-mac:
    if: contains(github.event.base_ref, 'refs/heads/main')
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma client
        run: bun run db:generate

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: bun run build:mac

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: |
            dist/*.dmg
            dist/latest-mac.yml

  release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            artifacts/windows/*
            artifacts/macos/*
